export const FETCH_VIDEOS_REQUEST="FETCH_VIDEOS_REQUEST";
export const FETCH_VIDEOS_SUCCESS="FETCH_VIDEOS_SUCCESS";
export const PREVIOUSLY_VIDEOS="PREVIOUSLY_VIDEOS" ;
export const HISTORY="HISTORY";
export const GET_VALUE="GET_VALUE";
